name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    uses: nushankodikara/reusable-workflows/.github/workflows/docker-publish.yaml@main
    with:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_image_and_tag: ${{ secrets.DOCKERHUB_USERNAME }}/auto-workshop-manager:latest
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
