name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-latest:
    uses: nushankodikara/reusable-workflows/.github/workflows/docker-publish.yaml@main
    with:
      docker_username: ${{ vars.DOCKERHUB_USERNAME }}
      docker_image_and_tag: ${{ vars.DOCKERHUB_USERNAME }}/auto-workshop-manager:latest
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-versioned:
    uses: nushankodikara/reusable-workflows/.github/workflows/docker-publish.yaml@main
    with:
      docker_username: ${{ vars.DOCKERHUB_USERNAME }}
      docker_image_and_tag: ${{ vars.DOCKERHUB_USERNAME }}/auto-workshop-manager:v1.0.${{ github.run_number }}
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
